from django.db import models

# Create your models here.
class Compounds(models.Model):
    common_name = models.CharField(max_length=255)
    ref = models.CharField(max_length=255)
    IUPAC_name = models.CharField(max_length=255)
    CAS_number = models.CharField(max_length=255)
    formula = models.CharField(max_length=255)
    C = models.FloatField()
    H = models.FloatField()
    N = models.FloatField()
    O = models.FloatField()
    S = models.FloatField()
    P = models.FloatField()
    canocical_smile = models.CharField(max_length=255)
    InchI = models.CharField(max_length=255)
    molecular_weight = models.FloatField()
    pKa = models.FloatField()
    logP = models.FloatField()
    logS = models.FloatField()
    polar_surface_area = models.FloatField()
    polarizability = models.FloatField()
    hydrogen_acceptor = models.FloatField()
    hydrogen_donor = models.FloatField()
    HOMO_1 = models.FloatField()
    HOMO = models.FloatField()
    LUMO = models.FloatField()
    ionization_energy = models.FloatField()
    electron_affinity = models.FloatField()
    electronegativity = models.FloatField()
    hardness = models.FloatField()
    electrophilicity  = models.FloatField()
    delta_NFe  = models.FloatField()
    IE_EXP  = models.FloatField()
